language: objective-c
osx_image: xcode9.2

before_script:
  - export LANG=en_US.UTF-8
script:
  - cd ./Testing/Xcode-desktop
  - xcodebuild -workspace YapDatabaseTesting.xcworkspace -scheme YapDatabaseTesting clean
  - xcodebuild -workspace YapDatabaseTesting.xcworkspace -scheme YapDatabaseTesting -configuration release test
